//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_DAL.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Designation { get; set; }
        public Nullable<int> Emp_Age { get; set; }
        public Nullable<decimal> Emp_Salary { get; set; }
        public Nullable<decimal> Emp_MobileNo { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_Address { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
